name: Create package on release

on:
  release:
    types:
      - created

jobs:
  packaging:
    name: Package the extension for Extension Manager
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5

      - name: Install translation tools
        run: sudo apt-get install -y make gettext

      - name: Install NodeJS 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install the dependencies
        run: yarn install --frozen-lockfile

      - name: Build and package the extension
        run: yarn package

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/gnome-github-manager-${{ github.event.release.tag_name }}.zip
